name: candy_bars
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  injectable: ^1.5.3
  stacked: ^2.3.15
  supabase_flutter: 1.0.0-dev.4
    # path: ../packages/supabase-flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  injectable_generator: ^1.5.4

flutter:
  uses-material-design: true

  assets:
    - .env